  controller_manager_ns: ''
  controller_list:
    - name: poppy_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - abs_z
        - bust_y
        - bust_x
        - head_z
        - head_y
        - l_shoulder_y
        - l_shoulder_x
        - l_arm_z
        - l_elbow_y
        - r_shoulder_y
        - r_shoulder_x
        - r_arm_z
        - r_elbow_y