# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  abs_z:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  bust_x:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  bust_y:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  head_y:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  head_z:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm_z:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow_y:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_x:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_y:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm_z:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow_y:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_x:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_y:
    has_velocity_limits: true
    max_velocity: 7
    has_acceleration_limits: false
    max_acceleration: 0